In [2]:
import pandas as pd

### Series
Series is a 1D Labelled Array

#### Initializing

In [3]:
# auto index
s = pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
# custom index
s2 = pd.Series([10,20,30,40], [7,1,4,2])
print(s, end="\n\n")

s3 = pd.Series([10,20,30,40], ['a','b','c','d'])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

0    10
1    20
2    30
3    40
dtype: int64

#### Accessing Values

In [5]:
# You can access values through index
print(s3['a'])
print(s[1])

10
20

#### Vector Like Operations

In [6]:
print(s+5)  # Add 5 to all values of 5
print(s*2)  # Multiply all values of s with 2
print(s.mean()) # Avg of all values of s

0    15
1    25
2    35
3    45
dtype: int64
0    20
1    40
2    60
3    80
dtype: int64
25.0

### Dataframe
Dataframe is a collection of series. <br>
It is a 2D table of rows and columns.

In [16]:
data = {
    "Name": ["Shail", "Raj", "Rohan"],
    "Age": [21, 18, 32],
    "City": ["Ahmedabad", "Mumbai", "Rajkot"]
}

df = pd.DataFrame(data)
df

    Name  Age       City
0  Shail   21  Ahmedabad
1    Raj   18     Mumbai
2  Rohan   32     Rajkot

#### Basic DataFrame Functions

In [8]:
df.head()   #Prints first 5 rows

    Name  Age       City
0  Shail   21  Ahmedabad
1    Raj   18     Mumbai
2  Rohan   32     Rajkot

In [9]:
df.tail(2)  #Prints Last 2 rows

    Name  Age    City
1    Raj   18  Mumbai
2  Rohan   32  Rajkot

In [10]:
df.shape    #Gives size of df

(3, 3)

In [11]:
df.columns  #Gives info about the columns

Index(['Name', 'Age', 'City'], dtype='object')

In [12]:
df.info()   #Data types and memory info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [13]:
df.describe()   #Summary stats(mean, avg, count, etc)

             Age
count   3.000000
mean   23.666667
std     7.371115
min    18.000000
25%    19.500000
50%    21.000000
75%    26.500000
max    32.000000