In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/people.csv")
df.head(3)

,Index,User Id,First Name,Last Name,Age,Sex,Email,Phone,Date of birth,Job Title,City,Salary
0,1,8717bbf45cCDbEe,Shelia,Mahoney,33,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer,Chennai,72000
1,2,3d5AD30A4cD38ed,Jo,Rivers,39,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer,Mumbai,292000
2,3,810Ce0F276Badec,Sheryl,Lowery,41,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy,Kolkata,60000

In [24]:
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Darth"],
    "Age": [24, 27, 22, 30],
    "City": ["Delhi", "Mumbai", "Chennai", "Ahmedabad"]
}, index=["a", "b", "c", "d"])

display(df1)

      Name  Age       City
a    Alice   24      Delhi
b      Bob   27     Mumbai
c  Charlie   22    Chennai
d    Darth   30  Ahmedabad

### Selecting Columns

In [4]:
df["Email"]

0                pwarner@example.org
1      fergusonkatherine@example.net
2                fhoward@example.org
3              zjohnston@example.com
4                   elin@example.net
                   ...
995           lyonsdaisy@example.net
996          dariusbryan@example.com
997           georgechan@example.org
998              wanda04@example.net
999          deannablack@example.org
Name: Email, Length: 1000, dtype: object

In [5]:
df[["First Name", "Last Name"]]

    First Name Last Name
0       Shelia   Mahoney
1           Jo    Rivers
2       Sheryl    Lowery
3      Whitney    Hooper
4      Lindsey      Rice
..         ...       ...
995       Kurt    Bryant
996      Donna     Barry
997      Cathy  Mckinney
998   Jermaine    Phelps
999        Lee      Tran

[1000 rows x 2 columns]

In [26]:
df["Full Name"] = df["First Name"] + " " + df["Last Name"]
df["Full Name"]

0       Shelia Mahoney
1            Jo Rivers
2        Sheryl Lowery
3       Whitney Hooper
4         Lindsey Rice
            ...
995        Kurt Bryant
996        Donna Barry
997     Cathy Mckinney
998    Jermaine Phelps
999           Lee Tran
Name: Full Name, Length: 1000, dtype: object

### Selecting Rows

In [7]:
# iloc: Integer Location
df1.iloc[2]  #3rd row

Name    Charlie
Age          22
City    Chennai
Name: c, dtype: object

In [8]:
# loc: Location
df1.loc['a']    # custom label (index)

Name    Alice
Age        24
City    Delhi
Name: a, dtype: object

### Using loc for rows & columns

In [27]:
df.loc[4, "Full Name"]

'Lindsey Rice'

In [10]:
df.loc[3:6]

,Index,User Id,First Name,Last Name,Age,Sex,Email,Phone,Date of birth,Job Title,City,Salary,Full Name
3,4,BF2a889C00f0cE1,Whitney,Hooper,31,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist,Bihar,495000,Whitney Hooper
4,5,9afFEafAe1CBBB9,Lindsey,Rice,33,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer,Mumbai,131000,Lindsey Rice
5,6,aF75e6dDEBC5b66,Sherry,Caldwell,59,Male,kaitlin13@example.net,8537800927,1917-08-06,Higher education lecturer,Chennai,484000,Sherry Caldwell
6,7,efeb05c7Cc94EA3,Ernest,Hoffman,40,Male,jeffharvey@example.com,093.655.7480x7895,1984-12-22,Health visitor,Chennai,400000,Ernest Hoffman

In [11]:
df.loc[:, ["User Id", "First Name"]]

             User Id First Name
0    8717bbf45cCDbEe     Shelia
1    3d5AD30A4cD38ed         Jo
2    810Ce0F276Badec     Sheryl
3    BF2a889C00f0cE1    Whitney
4    9afFEafAe1CBBB9    Lindsey
..               ...        ...
995  fedF4c7Fd9e7cFa       Kurt
996  ECddaFEDdEc4FAB      Donna
997  2adde51d8B8979E      Cathy
998  Fb2FE369D1E171A   Jermaine
999  8b756f6231DDC6e        Lee

[1000 rows x 2 columns]

In [12]:
df.loc[8:10, ["User Id", "First Name"]]

            User Id First Name
8   421fAB9a3b98F30     Cheryl
9   4A42Fe10dB717CB      Harry
10  44FAA9C3CE8DB2B      Casey

### Using iloc for rows & columns

In [30]:
df.iloc[2, 5]

'Female'

In [14]:
df.iloc[1:5]   # rows 1 to 4

,Index,User Id,First Name,Last Name,Age,Sex,Email,Phone,Date of birth,Job Title,City,Salary,Full Name
1,2,3d5AD30A4cD38ed,Jo,Rivers,39,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer,Mumbai,292000,Jo Rivers
2,3,810Ce0F276Badec,Sheryl,Lowery,41,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy,Kolkata,60000,Sheryl Lowery
3,4,BF2a889C00f0cE1,Whitney,Hooper,31,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist,Bihar,495000,Whitney Hooper
4,5,9afFEafAe1CBBB9,Lindsey,Rice,33,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer,Mumbai,131000,Lindsey Rice

In [15]:
df.iloc[0:5, 3:5]

  Last Name  Age
0   Mahoney   33
1    Rivers   39
2    Lowery   41
3    Hooper   31
4      Rice   33

### Filtering Rows

In [16]:
df1[df1["Age"] > 25]

    Name  Age       City
b    Bob   27     Mumbai
d  Darth   30  Ahmedabad

In [17]:
df1[df1["City"] == "Mumbai"].loc[:, ["Name","City"]]

  Name    City
b  Bob  Mumbai

In [18]:
df[df["First Name"].str.contains("Eli")]

,Index,User Id,First Name,Last Name,Age,Sex,Email,Phone,Date of birth,Job Title,City,Salary,Full Name
468,469,eb2A96D54cAb5c6,Elijah,Barnett,54,Male,hayley69@example.com,187-629-0069x666,1907-03-19,Minerals surveyor,Ahmedabad,332000,Elijah Barnett
652,653,BA9FCDFCed8a434,Elijah,Roberts,27,Female,janet65@example.com,261.518.3562x193,1973-01-04,"Biochemist, clinical",Kolkata,65000,Elijah Roberts
721,722,BC35A8dAaE8A73e,Elizabeth,Pearson,22,Male,lisaflynn@example.org,0746123720,1982-07-15,"Loss adjuster, chartered",Bihar,305000,Elizabeth Pearson

In [19]:
df1[(df1["Age"] > 25) & (df1["City"] == "Ahmedabad")]

    Name  Age       City
d  Darth   30  Ahmedabad

In [20]:
df1[(df1["City"] == "Delhi") | (df1["City"] == "Mumbai")]

    Name  Age    City
a  Alice   24   Delhi
b    Bob   27  Mumbai

### Resetting Index

In [21]:
# After filtering, index may look weird (like 0, 3, 7).
df1 = df1[(df1["City"] == "Delhi") | (df1["City"] == "Ahmedabad")]
df1

    Name  Age       City
a  Alice   24      Delhi
d  Darth   30  Ahmedabad

In [ ]:
# We fix this using:
df1.reset_index(drop=True, inplace=True)
df1

    Name  Age       City
0  Alice   24      Delhi
1  Darth   30  Ahmedabad