In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("data/dirty_cafe_sales.csv")

In [3]:
data = {
    "Name": [
        "Alice Rick", "Bob Ray", "Charlie Frankenstien", "David Rolls", "Eve Stay", "Frank Goodman", "Grace Amberson",
        "Alice Rick", "Bob Ray", "Charlie Frankenstien", "Grace Amberson"
    ],
    "Age": [
        "0", "", " thirty ", "28", "-1", "NaN", "31",
        "0", "", " thirty ", "31"
    ],
    "City": [
        "Delhi", "Mumbai", "Chennai", "", "Kolkata", "Delhi", "Mumbai",
        "Delhi", "Mumbai", "Chennai", "Mumbai"
    ],
    "Salary": [
        "50000", "0", "52000", "48000", "not_available", "1", "",
        "50000", "0", "52000", ""
    ],
    "Gender": [
        "Male", "Female", "M", "Female", "Female", "Male", "F",
        "Male", "Female", "M", "F"
    ],
    "Date": [
        "2023-01-10", "10/02/2023", "March 3rd, 2023", "2023/15/04", "2023-06-25",
        "25-13-2023", "2023-12-05",
        "2023-01-10", "10/02/2023", "March 3rd, 2023", "2023-12-05"
    ],
    "email": [
        "alice@facebook.com", "bob@gmail.com", "charlie@yahoo.co.in", "david@gmail.com",
        "eve@gmail.com", "frank@gmail.com", "grace@gmail.com",
        "alice@facebook.com", "bob_alt@gmail.com", "charlie@yahoo.co.in", "grace@gmail.com"
    ]
}

df2 = pd.DataFrame(data)
display(df2)

,Name,Age,City,Salary,Gender,Date,email
0,Alice Rick,0,Delhi,50000,Male,2023-01-10,alice@facebook.com
1,Bob Ray,,Mumbai,0,Female,10/02/2023,bob@gmail.com
2,Charlie Frankenstien,thirty,Chennai,52000,M,"March 3rd, 2023",charlie@yahoo.co.in
3,David Rolls,28,,48000,Female,2023/15/04,david@gmail.com
4,Eve Stay,-1,Kolkata,not_available,Female,2023-06-25,eve@gmail.com
5,Frank Goodman,NaN,Delhi,1,Male,25-13-2023,frank@gmail.com
6,Grace Amberson,31,Mumbai,,F,2023-12-05,grace@gmail.com
7,Alice Rick,0,Delhi,50000,Male,2023-01-10,alice@facebook.com
8,Bob Ray,,Mumbai,0,Female,10/02/2023,bob_alt@gmail.com
9,Charlie Frankenstien,thirty,Chennai,52000,M,"March 3rd, 2023",charlie@yahoo.co.in
10,Grace Amberson,31,Mumbai,,F,2023-12-05,grace@gmail.com

### Checking Missing Values (NaN)

In [4]:
# na stands for Not Available

df.isna()
# Checks if any value is missing.
# If missing, it returns True in that cell

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,True,False,False
9996,False,True,False,True,False,False,True,False
9997,False,False,False,False,False,False,True,False
9998,False,False,False,True,False,False,True,False
9999,False,False,False,False,False,False,False,False

In [5]:
df.isna().sum()
# Count missing values per column

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

### dropna() — Remove rows with NaN

In [6]:
df.dropna()
# Will not change values. You will have to take it in a variable or reassign it.

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9984,TXN_3142496,Smoothie,UNKNOWN,4.0,4.0,Cash,Takeaway,2023-07-27
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9992,TXN_2739140,Smoothie,4,4.0,16.0,UNKNOWN,In-store,2023-07-05
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [7]:
df.dropna(how="all")
# Remove rows only if all columns are NaN

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [8]:
# df1 = df    # Will create a pointer ❌
df1 = df.copy() # Will create a new copy ✅
df1.dropna(inplace=True)
# Changes the original DataFrame

df1

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9984,TXN_3142496,Smoothie,UNKNOWN,4.0,4.0,Cash,Takeaway,2023-07-27
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9992,TXN_2739140,Smoothie,4,4.0,16.0,UNKNOWN,In-store,2023-07-05
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

### fillna() — Replace missing values

In [9]:
# Fill NaN with a fixed value
df3 = df.fillna(0)
df3.isna().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [10]:
df3 = df.copy()

# Convert all non numeric data(outliers/errors) to numeric
df3["Quantity"] = pd.to_numeric(df3["Quantity"], errors="coerce")

# Fill a column with mean value
df3["Quantity"] = df3["Quantity"].fillna(df3["Quantity"].mean())
df3.isna().sum()

Transaction ID         0
Item                 333
Quantity               0
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

### replace() — Replace ANY value

In [27]:
df2["Gender"] = df2["Gender"].replace({"Male": "M", "Female": "F"})
df2["Gender"]

0     M
1     F
2     M
3     F
4     F
5     M
6     F
7     M
8     F
9     M
10    F
Name: Gender, dtype: object

In [12]:
# Replace multiple values
df2 = df2.replace(["0", "-1", "1"], value="Error")
df2[df2["Age"].str.contains("Error")]

,Name,Age,City,Salary,Gender,Date,email
0,Alice Rick,Error,Delhi,50000,M,2023-01-10,alice@facebook.com
4,Eve Stay,Error,Kolkata,not_available,F,2023-06-25,eve@gmail.com
7,Alice Rick,Error,Delhi,50000,M,2023-01-10,alice@facebook.com

### Changing Data Types — astype()

In [13]:
np.dtype(df3["Quantity"])

dtype('float64')

In [14]:
df3["Quantity"] = df3["Quantity"].astype(int)
np.dtype(df3["Quantity"])

dtype('int64')

In [15]:
df3["Quantity"] = df3["Quantity"].astype(float)
np.dtype(df3["Quantity"])

dtype('float64')

In [16]:
df3["Quantity"] = df3["Quantity"].astype(str)
print(np.dtype(df3["Quantity"]))

object

In [17]:
df2["Date"] = pd.to_datetime(df2["Date"], errors="coerce")
display(df2)

df2["Date"] = pd.to_datetime(df2["Date"])
print(np.dtype(df2["Date"]))

,Name,Age,City,Salary,Gender,Date,email
0,Alice Rick,Error,Delhi,50000,M,2023-01-10,alice@facebook.com
1,Bob Ray,,Mumbai,Error,F,NaT,bob@gmail.com
2,Charlie Frankenstien,thirty,Chennai,52000,M,NaT,charlie@yahoo.co.in
3,David Rolls,28,,48000,F,NaT,david@gmail.com
4,Eve Stay,Error,Kolkata,not_available,F,2023-06-25,eve@gmail.com
5,Frank Goodman,NaN,Delhi,Error,M,NaT,frank@gmail.com
6,Grace Amberson,31,Mumbai,,F,2023-12-05,grace@gmail.com
7,Alice Rick,Error,Delhi,50000,M,2023-01-10,alice@facebook.com
8,Bob Ray,,Mumbai,Error,F,NaT,bob_alt@gmail.com
9,Charlie Frankenstien,thirty,Chennai,52000,M,NaT,charlie@yahoo.co.in
10,Grace Amberson,31,Mumbai,,F,2023-12-05,grace@gmail.com

datetime64[ns]

### Removing Duplicates

In [18]:
display(df2)
df2.duplicated()

,Name,Age,City,Salary,Gender,Date,email
0,Alice Rick,Error,Delhi,50000,M,2023-01-10,alice@facebook.com
1,Bob Ray,,Mumbai,Error,F,NaT,bob@gmail.com
2,Charlie Frankenstien,thirty,Chennai,52000,M,NaT,charlie@yahoo.co.in
3,David Rolls,28,,48000,F,NaT,david@gmail.com
4,Eve Stay,Error,Kolkata,not_available,F,2023-06-25,eve@gmail.com
5,Frank Goodman,NaN,Delhi,Error,M,NaT,frank@gmail.com
6,Grace Amberson,31,Mumbai,,F,2023-12-05,grace@gmail.com
7,Alice Rick,Error,Delhi,50000,M,2023-01-10,alice@facebook.com
8,Bob Ray,,Mumbai,Error,F,NaT,bob_alt@gmail.com
9,Charlie Frankenstien,thirty,Chennai,52000,M,NaT,charlie@yahoo.co.in
10,Grace Amberson,31,Mumbai,,F,2023-12-05,grace@gmail.com

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9      True
10     True
dtype: bool

In [19]:
# Remove duplicate rows
df2.drop_duplicates()

,Name,Age,City,Salary,Gender,Date,email
0,Alice Rick,Error,Delhi,50000,M,2023-01-10,alice@facebook.com
1,Bob Ray,,Mumbai,Error,F,NaT,bob@gmail.com
2,Charlie Frankenstien,thirty,Chennai,52000,M,NaT,charlie@yahoo.co.in
3,David Rolls,28,,48000,F,NaT,david@gmail.com
4,Eve Stay,Error,Kolkata,not_available,F,2023-06-25,eve@gmail.com
5,Frank Goodman,NaN,Delhi,Error,M,NaT,frank@gmail.com
6,Grace Amberson,31,Mumbai,,F,2023-12-05,grace@gmail.com
8,Bob Ray,,Mumbai,Error,F,NaT,bob_alt@gmail.com

In [20]:
# Remove duplicates in one column
df2.drop_duplicates(subset="email")

,Name,Age,City,Salary,Gender,Date,email
0,Alice Rick,Error,Delhi,50000,M,2023-01-10,alice@facebook.com
1,Bob Ray,,Mumbai,Error,F,NaT,bob@gmail.com
2,Charlie Frankenstien,thirty,Chennai,52000,M,NaT,charlie@yahoo.co.in
3,David Rolls,28,,48000,F,NaT,david@gmail.com
4,Eve Stay,Error,Kolkata,not_available,F,2023-06-25,eve@gmail.com
5,Frank Goodman,NaN,Delhi,Error,M,NaT,frank@gmail.com
6,Grace Amberson,31,Mumbai,,F,2023-12-05,grace@gmail.com
8,Bob Ray,,Mumbai,Error,F,NaT,bob_alt@gmail.com

In [21]:
# Keep only last occurrence
df2.drop_duplicates(keep="last")

,Name,Age,City,Salary,Gender,Date,email
1,Bob Ray,,Mumbai,Error,F,NaT,bob@gmail.com
3,David Rolls,28,,48000,F,NaT,david@gmail.com
4,Eve Stay,Error,Kolkata,not_available,F,2023-06-25,eve@gmail.com
5,Frank Goodman,NaN,Delhi,Error,M,NaT,frank@gmail.com
7,Alice Rick,Error,Delhi,50000,M,2023-01-10,alice@facebook.com
8,Bob Ray,,Mumbai,Error,F,NaT,bob_alt@gmail.com
9,Charlie Frankenstien,thirty,Chennai,52000,M,NaT,charlie@yahoo.co.in
10,Grace Amberson,31,Mumbai,,F,2023-12-05,grace@gmail.com

In [22]:
# Keep last
df2.drop_duplicates(keep="last")

,Name,Age,City,Salary,Gender,Date,email
1,Bob Ray,,Mumbai,Error,F,NaT,bob@gmail.com
3,David Rolls,28,,48000,F,NaT,david@gmail.com
4,Eve Stay,Error,Kolkata,not_available,F,2023-06-25,eve@gmail.com
5,Frank Goodman,NaN,Delhi,Error,M,NaT,frank@gmail.com
7,Alice Rick,Error,Delhi,50000,M,2023-01-10,alice@facebook.com
8,Bob Ray,,Mumbai,Error,F,NaT,bob_alt@gmail.com
9,Charlie Frankenstien,thirty,Chennai,52000,M,NaT,charlie@yahoo.co.in
10,Grace Amberson,31,Mumbai,,F,2023-12-05,grace@gmail.com

### String Operations

In [23]:
display(df2["Name"].str.upper())

0               ALICE RICK
1                  BOB RAY
2     CHARLIE FRANKENSTIEN
3              DAVID ROLLS
4                 EVE STAY
5            FRANK GOODMAN
6           GRACE AMBERSON
7               ALICE RICK
8                  BOB RAY
9     CHARLIE FRANKENSTIEN
10          GRACE AMBERSON
Name: Name, dtype: object

In [24]:
df2[df2["City"].str.contains("Del")]

            Name    Age   City Salary Gender       Date               email
0     Alice Rick  Error  Delhi  50000      M 2023-01-10  alice@facebook.com
5  Frank Goodman    NaN  Delhi  Error      M        NaT     frank@gmail.com
7     Alice Rick  Error  Delhi  50000      M 2023-01-10  alice@facebook.com

In [25]:
df2["Name"].str.strip()
# removes lingering front and back extra spaces

0               Alice Rick
1                  Bob Ray
2     Charlie Frankenstien
3              David Rolls
4                 Eve Stay
5            Frank Goodman
6           Grace Amberson
7               Alice Rick
8                  Bob Ray
9     Charlie Frankenstien
10          Grace Amberson
Name: Name, dtype: object

In [26]:
df2["email"].str.replace("@gmail.com", "")

0      alice@facebook.com
1                     bob
2     charlie@yahoo.co.in
3                   david
4                     eve
5                   frank
6                   grace
7      alice@facebook.com
8                 bob_alt
9     charlie@yahoo.co.in
10                  grace
Name: email, dtype: object