In [1]:
import pandas as pd
import numpy as np

### Sorting Data

In [2]:
df = pd.read_csv("data/people.csv")

In [21]:
display(df.head())

                           Email First Name  Age          User Id
0            pwarner@example.org     Shelia   33  8717bbf45cCDbEe
1  fergusonkatherine@example.net         Jo   39  3d5AD30A4cD38ed
2            fhoward@example.org     Sheryl   41  810Ce0F276Badec
3          zjohnston@example.com    Whitney   31  BF2a889C00f0cE1
4               elin@example.net    Lindsey   33  9afFEafAe1CBBB9

In [4]:
df.sort_values("First Name")

,Index,User Id,First Name,Last Name,Age,Sex,Email,Phone,Date of birth,Job Title,City,Salary
698,699,d5DEd272fDF5bEA,Aaron,Little,21,Male,mitchell36@example.com,001-721-367-2584x508,1972-03-07,Hydrographic surveyor,Chennai,376000
562,563,E6bB801aCD2F2a0,Aaron,Wheeler,36,Female,wilcoxalexis@example.net,051.164.3836x1685,1942-02-22,Investment analyst,Delhi,97000
59,60,4e03dA0BCAc82e3,Aaron,Page,30,Male,harrygallagher@example.com,849.500.6331x717,1981-03-11,Administrator,Gandhinagar,288000
35,36,BcdffBD402E5A23,Adrienne,Lambert,59,Male,marilyn91@example.org,157.425.5345,2019-06-16,Comptroller,Banglore,278000
343,344,3ede74A0eaa6EEc,Aimee,Bridges,21,Male,jbautista@example.com,7342847803,1960-03-23,"Nurse, children's",Rajkot,361000
...,...,...,...,...,...,...,...,...,...,...,...,...
258,259,cDbDF7B189fcfDb,Yolanda,Stanton,50,Male,cookeannette@example.net,149.501.1590x5315,1908-05-17,Banker,Rajkot,493000
913,914,89D52456EC4eECE,Yolanda,Wagner,31,Male,curtis23@example.org,045.558.9873,1931-08-18,Health physicist,Kolkata,36000
279,280,3aFf54f59dcFD2E,Yvette,Webster,55,Male,sonya26@example.com,795-860-8920,2006-08-14,Clothing/textile technologist,Gandhinagar,317000
667,668,0Aa56ae7D7fe82f,Yvette,Barrett,56,Male,michaelawillis@example.net,+1-104-262-6571x2783,1982-07-07,Tax inspector,Mumbai,244000
292,293,c1D6Ddced4Fe3eF,Zachary,Nixon,32,Female,claudiayoung@example.com,333-779-8097x2347,1986-09-12,"Scientist, physiological",Mumbai,279000

In [5]:
df.sort_values("First Name", ascending=False)

,Index,User Id,First Name,Last Name,Age,Sex,Email,Phone,Date of birth,Job Title,City,Salary
292,293,c1D6Ddced4Fe3eF,Zachary,Nixon,32,Female,claudiayoung@example.com,333-779-8097x2347,1986-09-12,"Scientist, physiological",Mumbai,279000
667,668,0Aa56ae7D7fe82f,Yvette,Barrett,56,Male,michaelawillis@example.net,+1-104-262-6571x2783,1982-07-07,Tax inspector,Mumbai,244000
279,280,3aFf54f59dcFD2E,Yvette,Webster,55,Male,sonya26@example.com,795-860-8920,2006-08-14,Clothing/textile technologist,Gandhinagar,317000
282,283,0F7Ccb72cbbCcD2,Yolanda,Miller,23,Male,pfrye@example.org,(997)139-9531x88690,1978-12-14,Senior tax professional/tax inspector,Mumbai,491000
258,259,cDbDF7B189fcfDb,Yolanda,Stanton,50,Male,cookeannette@example.net,149.501.1590x5315,1908-05-17,Banker,Rajkot,493000
...,...,...,...,...,...,...,...,...,...,...,...,...
343,344,3ede74A0eaa6EEc,Aimee,Bridges,21,Male,jbautista@example.com,7342847803,1960-03-23,"Nurse, children's",Rajkot,361000
35,36,BcdffBD402E5A23,Adrienne,Lambert,59,Male,marilyn91@example.org,157.425.5345,2019-06-16,Comptroller,Banglore,278000
562,563,E6bB801aCD2F2a0,Aaron,Wheeler,36,Female,wilcoxalexis@example.net,051.164.3836x1685,1942-02-22,Investment analyst,Delhi,97000
698,699,d5DEd272fDF5bEA,Aaron,Little,21,Male,mitchell36@example.com,001-721-367-2584x508,1972-03-07,Hydrographic surveyor,Chennai,376000
59,60,4e03dA0BCAc82e3,Aaron,Page,30,Male,harrygallagher@example.com,849.500.6331x717,1981-03-11,Administrator,Gandhinagar,288000

In [6]:
df.sort_values(["First Name", "Last Name"])

,Index,User Id,First Name,Last Name,Age,Sex,Email,Phone,Date of birth,Job Title,City,Salary
698,699,d5DEd272fDF5bEA,Aaron,Little,21,Male,mitchell36@example.com,001-721-367-2584x508,1972-03-07,Hydrographic surveyor,Chennai,376000
59,60,4e03dA0BCAc82e3,Aaron,Page,30,Male,harrygallagher@example.com,849.500.6331x717,1981-03-11,Administrator,Gandhinagar,288000
562,563,E6bB801aCD2F2a0,Aaron,Wheeler,36,Female,wilcoxalexis@example.net,051.164.3836x1685,1942-02-22,Investment analyst,Delhi,97000
35,36,BcdffBD402E5A23,Adrienne,Lambert,59,Male,marilyn91@example.org,157.425.5345,2019-06-16,Comptroller,Banglore,278000
343,344,3ede74A0eaa6EEc,Aimee,Bridges,21,Male,jbautista@example.com,7342847803,1960-03-23,"Nurse, children's",Rajkot,361000
...,...,...,...,...,...,...,...,...,...,...,...,...
258,259,cDbDF7B189fcfDb,Yolanda,Stanton,50,Male,cookeannette@example.net,149.501.1590x5315,1908-05-17,Banker,Rajkot,493000
913,914,89D52456EC4eECE,Yolanda,Wagner,31,Male,curtis23@example.org,045.558.9873,1931-08-18,Health physicist,Kolkata,36000
667,668,0Aa56ae7D7fe82f,Yvette,Barrett,56,Male,michaelawillis@example.net,+1-104-262-6571x2783,1982-07-07,Tax inspector,Mumbai,244000
279,280,3aFf54f59dcFD2E,Yvette,Webster,55,Male,sonya26@example.com,795-860-8920,2006-08-14,Clothing/textile technologist,Gandhinagar,317000
292,293,c1D6Ddced4Fe3eF,Zachary,Nixon,32,Female,claudiayoung@example.com,333-779-8097x2347,1986-09-12,"Scientist, physiological",Mumbai,279000

### Adding Columns

In [7]:
df["Full Name"] = df["First Name"] + " " + df["Last Name"]
display(df)

,Index,User Id,First Name,Last Name,Age,Sex,Email,Phone,Date of birth,Job Title,City,Salary,Full Name
0,1,8717bbf45cCDbEe,Shelia,Mahoney,33,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer,Chennai,72000,Shelia Mahoney
1,2,3d5AD30A4cD38ed,Jo,Rivers,39,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer,Mumbai,292000,Jo Rivers
2,3,810Ce0F276Badec,Sheryl,Lowery,41,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy,Kolkata,60000,Sheryl Lowery
3,4,BF2a889C00f0cE1,Whitney,Hooper,31,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist,Bihar,495000,Whitney Hooper
4,5,9afFEafAe1CBBB9,Lindsey,Rice,33,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer,Mumbai,131000,Lindsey Rice
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,fedF4c7Fd9e7cFa,Kurt,Bryant,57,Female,lyonsdaisy@example.net,021.775.2933,1959-01-05,Personnel officer,Mumbai,44000,Kurt Bryant
996,997,ECddaFEDdEc4FAB,Donna,Barry,54,Female,dariusbryan@example.com,001-149-710-7799x721,2001-10-06,Education administrator,Mumbai,430000,Donna Barry
997,998,2adde51d8B8979E,Cathy,Mckinney,45,Female,georgechan@example.org,+1-750-774-4128x33265,1918-05-13,Commercial/residential surveyor,Gandhinagar,330000,Cathy Mckinney
998,999,Fb2FE369D1E171A,Jermaine,Phelps,59,Male,wanda04@example.net,(915)292-2254,1971-08-31,Ambulance person,Mumbai,422000,Jermaine Phelps
999,1000,8b756f6231DDC6e,Lee,Tran,57,Female,deannablack@example.org,079.752.5424x67259,1947-01-24,"Nurse, learning disability",Rajkot,331000,Lee Tran

In [8]:
df["DoubleAge"] = df["Age"] * 2
display(df.head(3))

,Index,User Id,First Name,Last Name,Age,Sex,Email,Phone,Date of birth,Job Title,City,Salary,Full Name,DoubleAge
0,1,8717bbf45cCDbEe,Shelia,Mahoney,33,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer,Chennai,72000,Shelia Mahoney,66
1,2,3d5AD30A4cD38ed,Jo,Rivers,39,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer,Mumbai,292000,Jo Rivers,78
2,3,810Ce0F276Badec,Sheryl,Lowery,41,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy,Kolkata,60000,Sheryl Lowery,82

In [22]:
df["Adult"] = df["Age"].apply(lambda x: True if x>=21 else False)
display(df[["Age", "Adult"]].sort_values("Adult"))

     Age  Adult
444   20  False
97    20  False
433   18  False
209   19  False
435   20  False
..   ...    ...
344   21   True
345   48   True
346   59   True
381   36   True
999   57   True

[1000 rows x 2 columns]

### Removing Columns

In [10]:
df.drop("DoubleAge", axis=1, inplace=True)
# axis=0 -> rows
# axis=1 -> cols

In [11]:
df.drop(["Job Title", "Phone"], axis=1)

,Index,User Id,First Name,Last Name,Age,Sex,Email,Date of birth,City,Salary,Full Name,Adult
0,1,8717bbf45cCDbEe,Shelia,Mahoney,33,Male,pwarner@example.org,2014-01-27,Chennai,72000,Shelia Mahoney,True
1,2,3d5AD30A4cD38ed,Jo,Rivers,39,Female,fergusonkatherine@example.net,1931-07-26,Mumbai,292000,Jo Rivers,True
2,3,810Ce0F276Badec,Sheryl,Lowery,41,Female,fhoward@example.org,2013-11-25,Kolkata,60000,Sheryl Lowery,True
3,4,BF2a889C00f0cE1,Whitney,Hooper,31,Male,zjohnston@example.com,2012-11-17,Bihar,495000,Whitney Hooper,True
4,5,9afFEafAe1CBBB9,Lindsey,Rice,33,Female,elin@example.net,1923-04-15,Mumbai,131000,Lindsey Rice,True
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,fedF4c7Fd9e7cFa,Kurt,Bryant,57,Female,lyonsdaisy@example.net,1959-01-05,Mumbai,44000,Kurt Bryant,True
996,997,ECddaFEDdEc4FAB,Donna,Barry,54,Female,dariusbryan@example.com,2001-10-06,Mumbai,430000,Donna Barry,True
997,998,2adde51d8B8979E,Cathy,Mckinney,45,Female,georgechan@example.org,1918-05-13,Gandhinagar,330000,Cathy Mckinney,True
998,999,Fb2FE369D1E171A,Jermaine,Phelps,59,Male,wanda04@example.net,1971-08-31,Mumbai,422000,Jermaine Phelps,True
999,1000,8b756f6231DDC6e,Lee,Tran,57,Female,deannablack@example.org,1947-01-24,Rajkot,331000,Lee Tran,True

### apply() + lambda

In [12]:
df["Age"].apply(lambda x: x * 5)
# display(df["Age"].sort_values(ascending=True))

0      165
1      195
2      205
3      155
4      165
      ...
995    285
996    270
997    225
998    295
999    285
Name: Age, Length: 1000, dtype: int64

In [13]:
df["Full Name"] = df["Full Name"].apply(lambda x: x.strip().upper())
# This will remove any extra spaces in the beginning and the end, not in between.

In [14]:
df["Retirement"] = df["Age"].apply(lambda x: "Yes" if x > 55 else "No")
display(df[["Age", "Retirement"]].sort_values("Retirement",ascending=True))

     Age Retirement
0     33         No
638   38         No
640   53         No
641   26         No
643   23         No
..   ...        ...
358   56        Yes
138   56        Yes
136   59        Yes
614   56        Yes
999   57        Yes

[1000 rows x 2 columns]

### map() — replace values using a dictionary

In [15]:
df["Sex"] = df["Sex"].map({"Male": "", "Female": "F"})
display(df["Sex"])

0
1      F
2      F
3
4      F
      ..
995    F
996    F
997    F
998
999    F
Name: Sex, Length: 1000, dtype: object

In [16]:
# Replacing Unknown Values
df["Sex"] = df["Sex"].map({"": "Unknown"}).fillna(df["Sex"])
display(df["Sex"])

0      Unknown
1            F
2            F
3      Unknown
4            F
        ...
995          F
996          F
997          F
998    Unknown
999          F
Name: Sex, Length: 1000, dtype: object

### Binning / Categorizing numeric values

In [17]:
# Turn a numeric column into categories.
df["Age Group"] = pd.cut(
    df["Age"],          #The column we are categorizing
    bins=[0, 18, 50, 100],  #Age groups
    labels=["Child", "Adult", "Senior"] #Categories
)

# 0-18: Child
# 19-50: Adult
# 51-100: Senior

display(df[["Age", "Age Group"]].head(10))

   Age Age Group
0   33     Adult
1   39     Adult
2   41     Adult
3   31     Adult
4   33     Adult
5   59    Senior
6   40     Adult
7   52    Senior
8   18     Child
9   26     Adult

### Renaming Columns

In [18]:
df.rename(columns={"Sex": "Gender"}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          1000 non-null   int64
 1   User Id        1000 non-null   object
 2   First Name     1000 non-null   object
 3   Last Name      1000 non-null   object
 4   Age            1000 non-null   int64
 5   Gender         1000 non-null   object
 6   Email          1000 non-null   object
 7   Phone          1000 non-null   object
 8   Date of birth  1000 non-null   object
 9   Job Title      1000 non-null   object
 10  City           1000 non-null   object
 11  Salary         1000 non-null   int64
 12  Full Name      1000 non-null   object
 13  Adult          1000 non-null   bool
 14  Retirement     1000 non-null   object
 15  Age Group      1000 non-null   category
dtypes: bool(1), category(1), int64(3), object(11)
memory usage: 111.6+ KB

In [19]:
df.rename(columns={"Sex": "Gender", "Age": "Years", "First Name": "Fname", "Last Name": "Lname"}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          1000 non-null   int64
 1   User Id        1000 non-null   object
 2   Fname          1000 non-null   object
 3   Lname          1000 non-null   object
 4   Years          1000 non-null   int64
 5   Gender         1000 non-null   object
 6   Email          1000 non-null   object
 7   Phone          1000 non-null   object
 8   Date of birth  1000 non-null   object
 9   Job Title      1000 non-null   object
 10  City           1000 non-null   object
 11  Salary         1000 non-null   int64
 12  Full Name      1000 non-null   object
 13  Adult          1000 non-null   bool
 14  Retirement     1000 non-null   object
 15  Age Group      1000 non-null   category
dtypes: bool(1), category(1), int64(3), object(11)
memory usage: 111.6+ KB

### Reordering columns

In [20]:
df = df[["Email", "First Name", "Age", "User Id"]]
display(df)
# This will also drop the columns not specified

                             Email First Name  Age          User Id
0              pwarner@example.org     Shelia   33  8717bbf45cCDbEe
1    fergusonkatherine@example.net         Jo   39  3d5AD30A4cD38ed
2              fhoward@example.org     Sheryl   41  810Ce0F276Badec
3            zjohnston@example.com    Whitney   31  BF2a889C00f0cE1
4                 elin@example.net    Lindsey   33  9afFEafAe1CBBB9
..                             ...        ...  ...              ...
995         lyonsdaisy@example.net       Kurt   57  fedF4c7Fd9e7cFa
996        dariusbryan@example.com      Donna   54  ECddaFEDdEc4FAB
997         georgechan@example.org      Cathy   45  2adde51d8B8979E
998            wanda04@example.net   Jermaine   59  Fb2FE369D1E171A
999        deannablack@example.org        Lee   57  8b756f6231DDC6e

[1000 rows x 4 columns]